Dividend=int(input("Ingresar dividend"))
Divisor=int(input("Ingresar divisor"))
Quocient=(Dividend)//(Divisor)
Residu=(Dividend)%(Divisor)
print(f"Divisió: {Dividend}/{Divisor}")
print(f"Quocient: {Quocient}")
print(f"Residu: {Residu}")